story5lto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story5ltoApp.urls')),
]

story5ltoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'story5ltoApp'

urlpatterns = [
    path('', views.index, name='Homepage'),
    path('profil/', views.profil, name='profil'),
    path('keahlian/', views.Keahlian, name='Keahlian'),
    path('pengalaman/', views.Pengalaman, name='Pengalaman'),
    path('kontak/', views.Kontak, name='Kontak'),
    path('pageTambahan/', views.pageTambahan, name='pageTambahan'),
    path('jadwal/', views.jadwal, name='jadwal'),
    path('tambah/', views.tambahJadwal, name='tambah'),
    path('hapusJadwal/<jadwal_id>', views.hapusJadwal, name='hapus'),
]

story5ltoApp/models.py
from django.db import models

class Jadwal(models.Model):
    namaKegiatan = models.CharField(max_length=255)
    tanggal = models.DateField()
    jam = models.TimeField()
    tempat = models.CharField(max_length=255)
    kategori = models.CharField(max_length=255)


    def __str__(self):
        return self.namaKegiatan    

story5ltoApp/forms.py
from django import forms

class JadwalForm(forms.Form):
    namaKegiatan = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw', 'class' : 'form-control', 'placeholder' : 'Kegiatan', 'id' : 'namaKegiatan'}))
    tanggal = forms.DateField(widget = forms.DateInput(attrs={'style' : 'font-size: 1vw','class' : 'form-control', 'id' : 'tanggal', 'type' : 'date'}))
    jam = forms.TimeField(widget = forms.TimeInput(attrs={'style' : 'font-size: 1vw','class' : 'form-control', 'id' : 'jam', 'type' : 'time'}))
    tempat = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw','class' : 'form-control', 'placeholder' : 'Tempat', 'id' : 'tempat'}))
    kategori = forms.CharField(max_length=255, widget = forms.TextInput(attrs={'style' : 'font-size: 1vw','class' : 'form-control', 'placeholder' : 'Ketegori kegiatan', 'id' : 'kategori'}))

story5ltoApp/views.py
from django.shortcuts import render, redirect

from django.views.decorators.http import require_POST

from .models import Jadwal
from .forms import JadwalForm

def index(request):
    return render(request, 'Homepage.html')

def profil(request):
    return render(request, 'Profil.html')

def Keahlian(request):
    return render(request, 'Keahlian.html')

def Pengalaman(request):
    return render(request, 'Pengalaman.html')

def Kontak(request):
    return render(request, 'Kontak.html')

def pageTambahan(request):
    return render(request, 'pageTambahan.html')

def jadwal(request):
    list_jadwal = Jadwal.objects.order_by('tanggal')
    form = JadwalForm()
    context = {'list_jadwal' : list_jadwal, 'form' : form}
    return render(request, 'jadwal.html', context)

@require_POST
def tambahJadwal(request):
    form = JadwalForm(request.POST)

    jadwalBaru = Jadwal(namaKegiatan = request.POST['namaKegiatan'], tanggal = request.POST['tanggal'], jam = request.POST['jam'], tempat = request.POST['tempat'], kategori = request.POST['kategori'])
    jadwalBaru.save()
    
    return redirect('story5ltoApp:jadwal')


def hapusJadwal(request, jadwal_id):
    
    Jadwal.objects.filter(id=jadwal_id).delete()

    return redirect('story5ltoApp:jadwal')



# Create your views here.

story5ltoApp/templates/Homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <nav class="navbar navbar-expand-lg navbar-light bg-light row justify-content-center sticky-top">
            <a href="{% url 'story5ltoApp:profil' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Profil</p> 
            </a>
            <a href="{% url 'story5ltoApp:Pengalaman' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Pengalaman</p> 
            </a>
            <a href="{% url 'story5ltoApp:Keahlian' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Keahlian</p> 
            </a>
            <a href="{% url 'story5ltoApp:Kontak' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Kontak</p> 
            </a>
            <a href="{% url 'story5ltoApp:pageTambahan' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Page Tambahan</p> 
            </a> 
            <a href="{% url 'story5ltoApp:jadwal' %}">
                <p style="font-size: 2vw" class="btn-sm my-2 text-black-50">Jadwal</p> 
            </a> 
    </nav>
    <h1 style="font-size: 4.8vw" class="d-flex justify-content-center bg-light">Selamat Datang di Website ku!!!</h1>
    <img class= "rounded-circle" src="{% static 'images/image (1).png' %}" alt="maap" width="25%">
    <h1 style="font-size: 4.8vw" class="text-white">About Me!</h1>
    <P style="font-size: 2vw" class="bg-light">
        Lorem Ipsum is simply dummy text of the printing and typesetting industry.
         Lorem Ipsum has been the industry's standard dummy text ever since the 
         1500s, when an unknown printer took a galley of type and scrambled it to 
         make a type specimen book. It has survived not only five centuries, but 
         also the leap into electronic typesetting, remaining essentially unchanged. 
         It was popularised in the 1960s with the release of Letraset sheets 
         containing Lorem Ipsum passages, and more recently with desktop publishing
         software like Aldus PageMaker including versions of Lorem Ipsum.
    </P>
</body>
</html>

story5ltoApp/templates/Keahlian.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Keahlian</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
                <div class="card-body bg-light m-5">
                    <h1 style="font-size: 4.8vw" class="">Keahlian</h1>
                    <div class="d-flex justify-content-center">
                        <div class="card-body bg-secondary col-lg-4 d-flex">
                            <h2 style="font-size: 2.4vw"class="mr-3">Hard Skills</h2>
                            <P style="font-size: 2vw">
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                Lorem Ipsum has been the industry's standard dummy text ever since the 
                                1500s, when an unknown printer took a galley of type and scrambled it to 
                                make a type specimen book.
                            </P> 
                        </div>
                        <div class="card-body bg-secondary ml-5 col-lg-4 d-flex ">
                            <h2 style="font-size: 2.4vw"class="mr-3">Soft Skills</h2>
                            <P style="font-size: 2vw">
                                Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                Lorem Ipsum has been the industry's standard dummy text ever since the 
                                1500s, when an unknown printer took a galley of type and scrambled it to 
                                make a type specimen book.
                            </P> 
                        </div>
                    </div>
                    <button style="font-size: 2vw" class="m-5 btn btn-secondary" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
                </div>
            
</body>
</html>

story5ltoApp/templates/Kontak.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Kontak</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>

<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div class="card-body">
        <div class="card-body bg-light m-5 d-flex justify-content-center">
            <h1 style="font-size: 4.8vw">Contact me!!!</h1>
            <a href="https://www.instagram.com/sulthanzahrans/">
                <img class="img-fluid" src="{% static 'images/contact icon/instagram-icon-black-and-white-png-7.jpg' %}" class="rounded float-left">
            </a>
            <a href="https://www.facebook.com/profile.php?id=100007920976637" class="rounded float-center">
                <img class="img-fluid" src="{% static 'images/contact icon/icon-02-512.png' %}">
            </a>
            <a href="https://twitter.com/zahran0709">
                <img class="img-fluid" src="{% static 'images/contact icon/twitter-icon-png-black-13.jpg' %}" class="rounded float-center">
            </a>
        </div>
        <button style="font-size: 2vw" class="m-5 btn btn-secondary" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
    </div>

</body>
</html>

story5ltoApp/templates/Pengalaman.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pengalaman</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div class="card-body bg-light m-5">
        <h1 style="font-size: 4.8vw" class="">Pengalaman</h1>
        <div class="d-flex justify-content-center">
            <div class="card-body bg-secondary col-lg-4 d-flex">
                <h2 style="font-size: 2.4vw"class="mr-3">Organisasi</h2>
                <P style="font-size: 2vw">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 
                    1500s, when an unknown printer took a galley of type and scrambled it to 
                    make a type specimen book.
                </P> 
            </div>
            <div class="card-body bg-secondary ml-5 col-lg-4 d-flex ">
                <h2 style="font-size: 2.4vw" class="mr-3">Kepanitiaan</h2>
                <P style="font-size: 2vw">
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 
                    1500s, when an unknown printer took a galley of type and scrambled it to 
                    make a type specimen book.
                </P> 
            </div>
        </div>
        <button style="font-size: 2vw" class="m-5 btn btn-secondary" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
    </div>

</body>
</html>

story5ltoApp/templates/Profil.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Profil</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div class="d-flex justify-content-center card-body bg-light m-5 p-5">
        <img style="width:25vw ; min-width: 100px;" class= "ml-1" src="{% static 'images/FOTO 3x4_190917_0005.jpg' %}" alt="maap" style="width: 20%">
        <div style="font-size: 2vw" class="card-body bg-secondary ml-2 col-lg-8 bg-light">   
            <h1 style="font-size: 4.8vw" >Profil</h1>
            
            Nama : Sulthan Zahran Sunata<br>
            
            NPM : 1806191585<br>
                        
            Angkatan : 2018<br>
                        
            Jurusan : Sistem Informasi<br>
                        
            Tempat Tanggal Lahir : Jakarta, 7 September 2000<br>
                        
            Alamat Tempat Tinggal : Jl. Daan Mogot<br>
                        
            Email : sulthan.zahran0709@gmail.com<br>
                        
            Nomor HP : 081288949960
        </div>
    </div>
    <button style="font-size: 2vw" class="d-flex justify-content-center m-5" type="button btn btn-secondary" onclick="javascript:history.back()"><span ></span>Back</button>
</body>
</html>

story5ltoApp/templates/jadwal.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Jadwal</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div class="card-body m-5">
        <h1 style="font-size: 4.8vw" class="d-flex justify-content-center text-white">Jadwal</h1><br>
        <form method="POST" action="{% url 'story5ltoApp:tambah' %}">
            {% csrf_token %}
            <h2 style="font-size: 2.4vw"class="text-white">Tambahkan jadwal</h2>
            <div class="form-group">
                <label style="font-size: 1vw" for="namaKegiatan" class="text-white">Nama kegiatan</label>
                {{ form.namaKegiatan }}
            </div>

            <div class="form-row">
            <div class="form-group col">
                <label style="font-size: 1vw" for="tanggal" class="text-white">Tanggal</label>
                {{ form.tanggal }}
            </div>
            <div class="form-group col">
                <label style="font-size: 1vw" for="jam" class="text-white">Jam</label>
                {{ form.jam }}
            </div>
            </div>

            <div class="form-group">
                <label style="font-size: 1vw" for="tempat" class="text-white">Tempat</label>
                {{ form.tempat }}
            </div>

            <div class="form-group">
                <label style="font-size: 1vw" for="kategori" class="text-white">Kategori</label>
                {{ form.kategori }}
            </div>

            <button style="font-size: 1vw" type="submit" class="btn btn-secondary mt-2 mr-2 mb-2">Submit</button>
            <button style="font-size: 1vw" type="reset" class="btn btn-secondary m-2">Reset</button>

        </form>
        <ul class="list-group">
                <li class="list-group-item active">Jadwal</li>
                {% for i in list_jadwal %}
                        <li class="list-group-item">{{ i.namaKegiatan }} | {{ i.tanggal }} | {{ i.jam }} | {{ i.tempat }} | {{ i.kategori }}
                                <a href="{% url 'story5ltoApp:hapus' i.id %}"><button style="font-size: 1vw" class="btn btn-danger ">Hapus</button></a>
                {% endfor %}
              </ul>
        <a href="{% url 'story5ltoApp:Homepage' %}">
            <button style="font-size: 1vw" class="m-5 btn btn-secondary" type="button"><span ></span>Back</button>
        </a>
        
    </div>
    </body>
</html>

story5ltoApp/templates/pageTambahan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Page Tambahan</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
</head>
<body background = "{% static 'images/joseph-chan-sBc8oen_ocg-unsplash.jpg' %}">
    <div>
        <p style="font-size: 3.6vw" class="text-center text-white mt-5">
            Coming soon...
        </p>
    </div>
    <button style="font-size: 2vw" class="m-5 btn btn-secondary" type="button" onclick="javascript:history.back()"><span ></span>Back</button>
</body>
</html>